package it.polimi.ingsw.Cards.Enums;

public enum GoalStates {
    //goals
    TWO_FOR_TWO_FEATHERS, TWO_FOR_TWO_SALT, TWO_FOR_TWO_PAPER,
    THREE_FOR_COMBO,

    TWO_FOR_THREE_FUNGUS, TWO_FOR_THREE_WOLF, TWO_FOR_THREE_LEAF, TWO_FOR_THREE_BUTTERFLY,
    TWO_FOR_RED_STAIRCASE, TWO_FOR_BLUE_STAIRCASE, TWO_FOR_GREEN_STAIRCASE, TWO_FOR_PURPLE_STAIRCASE,
    THREE_FOR_RED_L, THREE_FOR_BLUE_L, THREE_FOR_GREEN_L, THREE_FOR_PURPLE_L,

}
