package it.polimi.ingsw.Cards.Enums;

public enum PlayCondition {


    TWO_SAME_ONE_RED,TWO_SAME_ONE_BLUE, TWO_SAME_ONE_GREEN, TWO_SAME_ONE_PURPLE,
    THREE_SAME, THREE_SAME_ONE_RED, THREE_SAME_ONE_BLUE, THREE_SAME_ONE_GREEN, THREE_SAME_ONE_PURPLE,
    FIVE_SAME;

}
