package it.polimi.ingsw.ServerSide.Cards.Enums;

public enum StartingPoints {

    STARTING_ONE_PURPLE, STARTING_ONE_RED, STARTING_ONE_RED_ONE_GREEN,
    STARTING_ONE_BLUE_ONE_PURPLE, STARTING_ONE_BLUE_ONE_PURPLE_ONE_GREEN, STARTING_ONE_GREEN_ONE_BLUE_ONE_RED;

}
